### ISSUE TITLE
Rust-in-Flutter was renamed to Rinf

### ISSUE THREAD

**Issue by temeddix** [getong/flutter_workspace_example#1]
Hi, I have noticed that you were creating a wonderful project here with Rust-In-Flutter :)

`rust_in_flutter` has been renamed to `rinf`, so what do you think about replacing the content?

BEFORE: https://pub.dev/packages/rust_in_flutter
AFTER: https://pub.dev/packages/rinf

**Comment by getong** [comment]
rinf_example is uploaded. Thanks.
